description: "This is an example query for Joe."

# optional cache
cache:
  # 0 = None, 1 = by keys (+ optional ttl), 2 = by ttl
  type: 1
  # expression parameters to use for caching
  keys: [table_name]
  # ttl in seconds
  ttl: 30

# optional defaults
defaults:
  table_name: tables

# the query itself
query:
  SELECT * FROM information_schema.tables WHERE table_name = {table_name}

# create charts
views:
  bar: example_view.go