description: "Top players by access points."

# optional cache
cache:
  # 0 = None, 1 = by keys (+ optional ttl), 2 = by ttl
  type: 1
  # expression parameters to use for caching
  keys: [limit]
  # ttl in seconds
  ttl: 30

# the query itself
query:
  SELECT  u.updated_at as active_at, u.name, u.fingerprint, u.country, COUNT(a.id) AS networks FROM units u
  INNER JOIN access_points a ON u.id = a.unit_id GROUP BY u.id ORDER BY networks DESC LIMIT {limit}

# optional default values for the parameters
defaults:
  limit: 25

# define a chart
views:
  bars: example_view.go
